assetic:
    debug:          %kernel.debug%
    use_controller: false
    variables:
        locale: [en, fr, es, nl, de, zh]
    node_paths: ['%kernel.root_dir%/../node_modules']
    filters:
        cssrewrite: ~
        less: ~
        cssmin:
            file: '%kernel.root_dir%/../vendor/natxet/CssMin/src/CssMin.php'
            apply_to: '\.css$|\.less$'
